[remote]
host = "127.0.0.1"
port = 22
username = ""
private_key = ""

[odas]
command = "odaslive"
args = ["-c", "odas.cfg", "-v"]
cwd = ""
log = "odaslive.log"

[streams]
listen_host = "127.0.0.1"
sst_port = 9000
ssl_port = 9001
sss_sep_port = 10000
sss_pf_port = 10010