[remote]
host = "172.21.16.139"
port = 22
username = "odas"
private_key = "~/.ssh/id_rsa"

[odas]
config_path = "/opt/odas/config/odas.cfg"
command = "odaslive -c /opt/odas/config/odas.cfg -v"

[streams]
sst_port = 9000
ssl_port = 9001
sss_sep_port = 10000
sss_pf_port = 10010
